export const SET_INF ="SET_INF"
export const SET_SELECTED_CATEGORY ="SET_SELECTED_CATEGORY"
export const SET_SELECTED_ARTICLE = 'SET_SELECTED_ARTICLE';
export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_TOKEN = "UPDATE_USER_TOKEN";
export const SET_USER_INFO = 'SET_USER_INFO';